const ACCOUNT_ROLES = Object.freeze({
  APPLICANT: "APPLICANT",
  COMPANY: "COMPANY",
  ADMIN: "ADMIN"
});

const ACCOUNT_STATUSES = Object.freeze({
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  SUSPENDED: "SUSPENDED"
});

const CV_LANGUAGES = Object.freeze({
  VI: "VI",
  EN: "EN"
});

const CV_STATUSES = Object.freeze({
  ACTIVE: "ACTIVE",
  DELETED: "DELETED"
});

const AI_TYPES = Object.freeze({
  CV_FEEDBACK: "CV_FEEDBACK",
  CV_TRANSLATION: "CV_TRANSLATION",
  CV_SCORING: "CV_SCORING",
  JOB_RECOMMENDATION: "JOB_RECOMMENDATION"
});

const AI_STATUSES = Object.freeze({
  PENDING: "PENDING",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED"
});

const VISIBILITIES = Object.freeze({
  PRIVATE: "PRIVATE",
  PUBLIC: "PUBLIC"
});

const ACCOUNT_ROLE_VALUES = Object.values(ACCOUNT_ROLES);
const ACCOUNT_STATUS_VALUES = Object.values(ACCOUNT_STATUSES);
const CV_LANGUAGE_VALUES = Object.values(CV_LANGUAGES);
const CV_STATUS_VALUES = Object.values(CV_STATUSES);
const AI_TYPE_VALUES = Object.values(AI_TYPES);
const AI_STATUS_VALUES = Object.values(AI_STATUSES);
const VISIBILITY_VALUES = Object.values(VISIBILITIES);

const PORTFOLIO_EXPERIENCE_TYPES = Object.freeze({
  EVENT: "event",
  PROJECT: "project",
  JOB: "job",
  INTERNSHIP: "internship",
  VOLUNTEER: "volunteer",
  COMPETITION: "competition",
  WORKSHOP: "workshop",
  COURSE: "course",
  CLUB: "club",
  PERSONAL_PROJECT: "personal-project",
  OTHER: "other"
});

const PORTFOLIO_EXPERIENCE_STATUSES = Object.freeze({
  DRAFT: "draft",
  PUBLISHED: "published",
  ARCHIVED: "archived"
});

const PORTFOLIO_EXPERIENCE_VISIBILITIES = Object.freeze({
  PRIVATE: "private",
  PORTFOLIO: "portfolio"
});

const PORTFOLIO_MOMENT_STATUSES = Object.freeze({
  DRAFT: "draft",
  READY: "ready"
});

const PORTFOLIO_ASSET_TYPES = Object.freeze({
  IMAGE: "image",
  VIDEO: "video",
  DOCUMENT: "document",
  CERTIFICATE: "certificate",
  OTHER: "other"
});

const PORTFOLIO_ASSET_USAGES = Object.freeze({
  MOMENT_MEDIA: "moment-media",
  EXPERIENCE_COVER: "experience-cover",
  EXPERIENCE_EVIDENCE: "experience-evidence"
});

const PORTFOLIO_CLOUDINARY_RESOURCE_TYPES = Object.freeze({
  IMAGE: "image",
  VIDEO: "video",
  RAW: "raw"
});

const PORTFOLIO_EVIDENCE_TYPES = Object.freeze({
  FILE: "file",
  CERTIFICATE: "certificate",
  GITHUB: "github",
  WEBSITE: "website",
  ARTICLE: "article",
  VIDEO: "video",
  OTHER: "other"
});

const PORTFOLIO_EVIDENCE_VERIFICATION_STATUSES = Object.freeze({
  UNVERIFIED: "unverified",
  DOCUMENT_PROVIDED: "document-provided",
  VERIFIED: "verified"
});

const values = <T extends Record<string, string>>(object: T) => Object.values(object);

const PORTFOLIO_EXPERIENCE_TYPE_VALUES = values(PORTFOLIO_EXPERIENCE_TYPES);
const PORTFOLIO_EXPERIENCE_STATUS_VALUES = values(PORTFOLIO_EXPERIENCE_STATUSES);
const PORTFOLIO_EXPERIENCE_VISIBILITY_VALUES = values(PORTFOLIO_EXPERIENCE_VISIBILITIES);
const PORTFOLIO_MOMENT_STATUS_VALUES = values(PORTFOLIO_MOMENT_STATUSES);
const PORTFOLIO_ASSET_TYPE_VALUES = values(PORTFOLIO_ASSET_TYPES);
const PORTFOLIO_ASSET_USAGE_VALUES = values(PORTFOLIO_ASSET_USAGES);
const PORTFOLIO_CLOUDINARY_RESOURCE_TYPE_VALUES = values(
  PORTFOLIO_CLOUDINARY_RESOURCE_TYPES
);
const PORTFOLIO_EVIDENCE_TYPE_VALUES = values(PORTFOLIO_EVIDENCE_TYPES);
const PORTFOLIO_EVIDENCE_VERIFICATION_STATUS_VALUES = values(
  PORTFOLIO_EVIDENCE_VERIFICATION_STATUSES
);

export {
  ACCOUNT_ROLES,
  ACCOUNT_ROLE_VALUES,
  ACCOUNT_STATUSES,
  ACCOUNT_STATUS_VALUES,
  CV_LANGUAGES,
  CV_LANGUAGE_VALUES,
  CV_STATUSES,
  CV_STATUS_VALUES,
  AI_TYPES,
  AI_TYPE_VALUES,
  AI_STATUSES,
  AI_STATUS_VALUES,
  VISIBILITIES,
  VISIBILITY_VALUES,
  PORTFOLIO_EXPERIENCE_TYPES,
  PORTFOLIO_EXPERIENCE_TYPE_VALUES,
  PORTFOLIO_EXPERIENCE_STATUSES,
  PORTFOLIO_EXPERIENCE_STATUS_VALUES,
  PORTFOLIO_EXPERIENCE_VISIBILITIES,
  PORTFOLIO_EXPERIENCE_VISIBILITY_VALUES,
  PORTFOLIO_MOMENT_STATUSES,
  PORTFOLIO_MOMENT_STATUS_VALUES,
  PORTFOLIO_ASSET_TYPES,
  PORTFOLIO_ASSET_TYPE_VALUES,
  PORTFOLIO_ASSET_USAGES,
  PORTFOLIO_ASSET_USAGE_VALUES,
  PORTFOLIO_CLOUDINARY_RESOURCE_TYPES,
  PORTFOLIO_CLOUDINARY_RESOURCE_TYPE_VALUES,
  PORTFOLIO_EVIDENCE_TYPES,
  PORTFOLIO_EVIDENCE_TYPE_VALUES,
  PORTFOLIO_EVIDENCE_VERIFICATION_STATUSES,
  PORTFOLIO_EVIDENCE_VERIFICATION_STATUS_VALUES
};
