const ACCOUNT_ROLES = Object.freeze({
  APPLICANT: "APPLICANT",
  COMPANY: "COMPANY",
  ADMIN: "ADMIN"
});

const ACCOUNT_STATUSES = Object.freeze({
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  SUSPENDED: "SUSPENDED"
});

const CV_LANGUAGES = Object.freeze({
  VI: "VI",
  EN: "EN"
});

const CV_STATUSES = Object.freeze({
  ACTIVE: "ACTIVE",
  DELETED: "DELETED"
});

const AI_TYPES = Object.freeze({
  CV_FEEDBACK: "CV_FEEDBACK",
  CV_TRANSLATION: "CV_TRANSLATION",
  CV_SCORING: "CV_SCORING",
  JOB_RECOMMENDATION: "JOB_RECOMMENDATION"
});

const AI_STATUSES = Object.freeze({
  PENDING: "PENDING",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED"
});

const ACCOUNT_ROLE_VALUES = Object.values(ACCOUNT_ROLES);
const ACCOUNT_STATUS_VALUES = Object.values(ACCOUNT_STATUSES);
const CV_LANGUAGE_VALUES = Object.values(CV_LANGUAGES);
const CV_STATUS_VALUES = Object.values(CV_STATUSES);
const AI_TYPE_VALUES = Object.values(AI_TYPES);
const AI_STATUS_VALUES = Object.values(AI_STATUSES);

export {
  ACCOUNT_ROLES,
  ACCOUNT_ROLE_VALUES,
  ACCOUNT_STATUSES,
  ACCOUNT_STATUS_VALUES,
  CV_LANGUAGES,
  CV_LANGUAGE_VALUES,
  CV_STATUSES,
  CV_STATUS_VALUES,
  AI_TYPES,
  AI_TYPE_VALUES,
  AI_STATUSES,
  AI_STATUS_VALUES
};
