const ACCOUNT_ROLES = Object.freeze({
  APPLICANT: "APPLICANT",
  COMPANY: "COMPANY",
  ADMIN: "ADMIN"
});

const ACCOUNT_STATUSES = Object.freeze({
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  SUSPENDED: "SUSPENDED"
});

module.exports = {
  ACCOUNT_ROLES,
  ACCOUNT_ROLE_VALUES: Object.values(ACCOUNT_ROLES),
  ACCOUNT_STATUSES,
  ACCOUNT_STATUS_VALUES: Object.values(ACCOUNT_STATUSES)
};
