const ACCOUNT_ROLES = Object.freeze({
  APPLICANT: "APPLICANT",
  COMPANY: "COMPANY",
  ADMIN: "ADMIN"
});

const ACCOUNT_STATUSES = Object.freeze({
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  SUSPENDED: "SUSPENDED"
});

const CV_LANGUAGES = Object.freeze({
  VI: "VI",
  EN: "EN"
});

const CV_STATUSES = Object.freeze({
  ACTIVE: "ACTIVE",
  DELETED: "DELETED"
});

const ACCOUNT_ROLE_VALUES = Object.values(ACCOUNT_ROLES);
const ACCOUNT_STATUS_VALUES = Object.values(ACCOUNT_STATUSES);
const CV_LANGUAGE_VALUES = Object.values(CV_LANGUAGES);
const CV_STATUS_VALUES = Object.values(CV_STATUSES);

export {
  ACCOUNT_ROLES,
  ACCOUNT_ROLE_VALUES,
  ACCOUNT_STATUSES,
  ACCOUNT_STATUS_VALUES,
  CV_LANGUAGES,
  CV_LANGUAGE_VALUES,
  CV_STATUSES,
  CV_STATUS_VALUES
};
